package app;

public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        panPlanning = new javax.swing.JPanel();
        panMatchs = new javax.swing.JPanel();
        panPersonnel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panPlanningLayout = new javax.swing.GroupLayout(panPlanning);
        panPlanning.setLayout(panPlanningLayout);
        panPlanningLayout.setHorizontalGroup(
            panPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        panPlanningLayout.setVerticalGroup(
            panPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Planning", panPlanning);

        javax.swing.GroupLayout panMatchsLayout = new javax.swing.GroupLayout(panMatchs);
        panMatchs.setLayout(panMatchsLayout);
        panMatchsLayout.setHorizontalGroup(
            panMatchsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        panMatchsLayout.setVerticalGroup(
            panMatchsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Matchs", panMatchs);

        javax.swing.GroupLayout panPersonnelLayout = new javax.swing.GroupLayout(panPersonnel);
        panPersonnel.setLayout(panPersonnelLayout);
        panPersonnelLayout.setHorizontalGroup(
            panPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        panPersonnelLayout.setVerticalGroup(
            panPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Personnel", panPersonnel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel panMatchs;
    private javax.swing.JPanel panPersonnel;
    private javax.swing.JPanel panPlanning;
    // End of variables declaration//GEN-END:variables
}
